"""Remove unused subcategory_id

Revision ID: 171d35aa41e0
Revises: bdf0881baf84
Create Date: 2025-04-21 11:51:18.491289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d35aa41e0'
down_revision = 'bdf0881baf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_device_framework_association') as batch_op:
        # 1) drop the FK that’s using framework_id
        batch_op.drop_constraint(
            'lesson_device_framework_association_ibfk_2',
            type_='foreignkey'
        )
        # 2) now you can drop the index
        batch_op.drop_index('subcategory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    # ### end Alembic commands ###
