"""Allow author to be null

Revision ID: 20ef3e7919be
Revises: d66b1c55f8cf
Create Date: 2025-01-15 10:50:20.344638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20ef3e7919be'
down_revision = 'd66b1c55f8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
