"""Renaming entire database for relation and attribute names

Revision ID: 371c2f1f8947
Revises: ec8f3ad5e076
Create Date: 2025-04-28 02:01:42.898761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '371c2f1f8947'
down_revision = 'ec8f3ad5e076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('lesson', 'laboratory_exercise')
    op.rename_table('lesson_category', 'laboratory_exercise_category')
    op.rename_table('lesson_level', 'laboratory_exercise_level')
    op.rename_table('lesson_image', 'laboratory_exercise_image')
    op.rename_table('lesson_doc', 'laboratory_exercise_doc')
    op.rename_table('lesson_device_framework_association', 'laboratory_exercise_device_framework_association')
    op.rename_table('lesson_simulation', 'laboratory_exercise_simulation')
    op.rename_table('lesson_category_association', 'laboratory_exercise_category_association')
    op.rename_table('lesson_level_association', 'laboratory_exercise_level_association')
    op.rename_table('author_lesson', 'author_laboratory_exercise')

    with op.batch_alter_table('laboratory_exercise_image') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('laboratory_exercise_doc') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('laboratory_exercise_device_framework_association') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('laboratory_exercise_simulation') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('laboratory_exercise_category_association') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('laboratory_exercise_level_association') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    with op.batch_alter_table('author_laboratory_exercise') as batch_op:
        batch_op.alter_column('lesson_id', new_column_name='laboratory_exercise_id',
            existing_type=sa.Integer, nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('laboratory_exercise', 'lesson')
    op.rename_table('laboratory_exercise_category', 'lesson_category')
    op.rename_table('laboratory_exercise_level', 'lesson_level')
    op.rename_table('laboratory_exercise_doc', 'lesson_doc')
    op.rename_table('laboratory_exercise_image', 'lesson_image')

    op.rename_table('author_laboratory_exercise', 'author_lesson')
    op.rename_table('laboratory_exercise_simulation', 'lesson_simulation')
    op.rename_table('laboratory_exercise_device_framework_association', 'lesson_device_framework_association')
    op.rename_table('laboratory_exercise_level_association', 'lesson_level_association')
    op.rename_table('laboratory_exercise_category_association', 'lesson_category_association')

    # ### end Alembic commands ###
