"""Changed DeviceFramework to a One-To-Many relationship

Revision ID: 49ac3e4cd44c
Revises: 7d3ed1873d65
Create Date: 2025-03-30 18:36:24.317982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49ac3e4cd44c'
down_revision = '7d3ed1873d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_framework_association')
    
    with op.batch_alter_table('device_framework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    with op.batch_alter_table('device_framework', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('device_id')

    op.create_table('device_framework_association',
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('framework_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='device_framework_association_ibfk_1'),
    sa.ForeignKeyConstraint(['framework_id'], ['device_framework.id'], name='device_framework_association_ibfk_2'),
    sa.PrimaryKeyConstraint('device_id', 'framework_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    # ### end Alembic commands ###
