"""Added simulation to device relation

Revision ID: 7d3ed1873d65
Revises: 90850c1f278b
Create Date: 2025-03-11 02:11:48.646572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3ed1873d65'
down_revision = '90850c1f278b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_framework_association',
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['device_framework.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('simulation_id', 'framework_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    with op.batch_alter_table('device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    op.drop_table('simulation_framework_association')
    # ### end Alembic commands ###
