"""Add docs for simulation-devices; and remove unique in the name of device frameworks

Revision ID: 85bbb1cf787b
Revises: 49ac3e4cd44c
Create Date: 2025-04-01 11:55:57.222657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85bbb1cf787b'
down_revision = '49ac3e4cd44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_device_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('doc_url', sa.String(length=2083), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_framework', schema=None) as batch_op:
        batch_op.drop_index('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.create_index('subcategory_id', ['framework_id'], unique=False)

    with op.batch_alter_table('device_framework', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.drop_table('simulation_device_document')
    # ### end Alembic commands ###
