"""Remove device<->lesson association

Revision ID: 8dcc12e424b1
Revises: ec8f3ad5e076
Create Date: 2025-04-22 12:26:03.781681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dcc12e424b1'
down_revision = '371c2f1f8947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_device',
    sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='lesson_device_ibfk_1'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='lesson_device_ibfk_2'),
    sa.PrimaryKeyConstraint('lesson_id', 'device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
