"""Added SupportedDevice

Revision ID: 8e898549b8db
Revises: 9064f241a700
Create Date: 2025-02-10 00:52:00.374436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e898549b8db'
down_revision = '9064f241a700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supported_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supported_device_simulation',
    sa.Column('supported_device_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.ForeignKeyConstraint(['supported_device_id'], ['supported_device.id'], ),
    sa.PrimaryKeyConstraint('supported_device_id', 'simulation_id')
    )
    op.create_table('supported_device_lesson',
    sa.Column('supported_device_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['supported_device_id'], ['supported_device.id'], ),
    sa.PrimaryKeyConstraint('supported_device_id', 'lesson_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supported_device_lesson')
    op.drop_table('supported_device_simulation')
    op.drop_table('supported_device')
    # ### end Alembic commands ###
