"""Added Slug to Lesson

Revision ID: 95618cd64874
Revises: 6326d264a1ff
Create Date: 2025-02-08 13:51:07.222321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95618cd64874'
down_revision = '6326d264a1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
