"""Added SimulationDoc

Revision ID: e23b428b9e5d
Revises: a6b5125f0a59
Create Date: 2025-02-14 00:45:03.223762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e23b428b9e5d'
down_revision = 'a6b5125f0a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('doc_url', sa.String(length=2083), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('simulation_doc')
    # ### end Alembic commands ###
