"""Remove unused subcategory_id

Revision ID: e3e4fb2501a3
Revises: 171d35aa41e0
Create Date: 2025-04-21 11:51:40.109038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e4fb2501a3'
down_revision = '171d35aa41e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'device_framework', ['framework_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_device_framework_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
