"""test change

Revision ID: e424ea02d723
Revises: a9ce80ee596b
Create Date: 2026-03-20 03:51:09.860065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e424ea02d723'
down_revision = 'a9ce80ee596b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # with op.batch_alter_table('author_laboratory_exercise', schema=None) as batch_op:
    #     batch_op.drop_index('lesson_id')

    # with op.batch_alter_table('laboratory_exercise_doc', schema=None) as batch_op:
    #     batch_op.drop_index('lesson_id')

    # with op.batch_alter_table('laboratory_exercise_image', schema=None) as batch_op:
    #     batch_op.drop_index('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_exercise_image', schema=None) as batch_op:
        batch_op.create_index('lesson_id', ['laboratory_exercise_id'], unique=False)

    with op.batch_alter_table('laboratory_exercise_doc', schema=None) as batch_op:
        batch_op.create_index('lesson_id', ['laboratory_exercise_id'], unique=False)

    with op.batch_alter_table('author_laboratory_exercise', schema=None) as batch_op:
        batch_op.create_index('lesson_id', ['laboratory_exercise_id'], unique=False)

    # ### end Alembic commands ###
