"""Removed LessonVideos and replaced them with a field in lessons, also added video_url in simulations

Revision ID: ec8fb5843c84
Revises: 7719a626bae2
Create Date: 2025-04-22 00:05:09.672831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec8fb5843c84'
down_revision = '7719a626bae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_video')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.Text(), nullable=True))

    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    op.create_table('lesson_video',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_url', mysql.VARCHAR(length=2083), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='lesson_video_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
